#!/bin/sh

set -e

SPREEDBOX_SERVICE_DEFAULTS="/etc/default/spreedbox-authd"
SPREEDBOX_SERVICE_USER="spreedbox-authd"
SPREEDBOX_SERVICE_GROUP="spreedbox-service"

KEY_BITS=4096
KEYS="/etc/spreedbox/auth/keys"

if [ -x "/usr/bin/libressl-openssl" ]; then
    OPENSSL="/usr/bin/libressl-openssl"
else
    OPENSSL="/usr/bin/openssl"
fi

if [ -e "$SPREEDBOX_SERVICE_DEFAULTS" ]; then
	. "$SPREEDBOX_SERVICE_DEFAULTS"
fi

rsa_keypair() {
	if [ ! -e "$KEYS/privkey.pem" ]; then
		now=$(date +%s)
		mkdir -p "$KEYS"
		# Create new private key.
		echo "Generating RSA keypair ..."
		oldumask=$(umask)
		umask 077
		$OPENSSL genrsa -out "$KEYS/privkey-$now.pem" $KEY_BITS
		umask $oldumask
		chown $SPREEDBOX_SERVICE_USER:$SPREEDBOX_SERVICE_GROUP "$KEYS/privkey-$now.pem" || true
		ln -sf privkey-$now.pem "$KEYS/privkey.pem"
	fi
}

case "$1" in
	firstboot|configure)
		rsa_keypair
		;;
	*)
		echo "helper called with unknown argument '$1'" >&2
		exit 0
		;;
esac
